# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 05:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_auto_20170308_0430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stripeuser',
            old_name='stripeID',
            new_name='stripeUserID',
        ),
    ]
